run:
  tests: false
  concurrency: 8
  skip-dirs:
    - vendor/

  skip-files:
    - "_easyjson.go"
    - ".pb.go"
    - ".svc.go"
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - revive
    - goimports
    - unparam
    - unconvert
    - megacheck
    - staticcheck
    - unused
    - gosimple
    - dupl
    - goconst
    - gocyclo
    - nakedret
    - exportloopref
    - gocritic
    - misspell

linters-settings:
  golint:
    min-confidence: 0.3
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 200
  lll:
    line-length: 150
  funlen:
    statements: 100
    lines: 160

output:
  format: tab

issues:
  # Not using default exclusions because we want to require comments on public
  # functions and tickets.
  exclude-use-default: false
  exclude:
    # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
    # golint: False positive when tests are defined in package 'test'
    - func name will be used as test\.Test.* by other packages, and that stutters; consider calling this
    # govet: Common false positives
    - (possible misuse of unsafe.Pointer|should have signature)

openapogenindocker:
  docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate \
  -i /local/checkout.yaml \
  -g go \
  -o /local/out/go
