version: '3'
#  docker-compose down --volumes

services:

  postgres-customer:
    image: postgres:latest
    container_name: postgres-customer
    env_file:
      - build/docker/customer/dev.customer.database.env
    ports:
      - "5555:5432/tcp"

  postgres-ticket:
    image: postgres:latest
    container_name: postgres-ticket
    env_file:
      - build/docker/ticket/dev.ticket.database.env
    ports:
      - "5556:5432/tcp"

#  docker run -it -p 27017:27017 --name mongo mongo:4 mongo
# MONGO_URI=mongodb://127.0.0.1:27217/bpm ./cbpm-backend
# docker run -p 27217:27017 --name dev-mongo -v -d mongo
