GRPCServer:
  AppVersion: 1.0.0docker
  Port: ":5001"
  CookieLifeTime: 360
  CsrfExpire: 15
  SessionExpire: 60
  SessionID: "SessionID"
  Mode: "Development"
  Timeout: 15
  ReadTimeout: 5
  WriteTimeout: 5
  MaxConnectionIdle: 5
  MaxConnectionAge: 5
  SessionPrefix: "session"
  CSRFPrefix: "csrf"
  SessionGrpcServicePort: ":5000"

GRPC:
  TicketServicePort: ":5001"

HttpServer:
  Port: ":8000"
  PprofPort: ":8001"
  Timeout: 15
  ReadTimeout: 5
  WriteTimeout: 5
  CookieLifeTime: 44640
  SessionCookieName: "session_token"

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

redis:
  RedisAddr: localhost:6379
  RedisPassword:
  RedisDb: 0
  RedisDefaultDB: 0
  MinIdleConn: 200
  PoolSize: 12000
  PoolTimeout: 240
  Password: ""
  DB: 0

postgres:
  PostgresqlHost: postgres-ticket
  PostgresqlPort: 5556
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDbname: postgres
  PostgresqlSslmode: "disable"
  PgDriver: postgres
