GRPCServer:
  AppVersion: 1.0.0
  Port: ":5001"
  CookieLifeTime: 360
  CsrfExpire: 15
  SessionExpire: 60
  SessionID: "SessionID"
  Mode: "Development"
  Timeout: 15
  ReadTimeout: 5
  WriteTimeout: 5
  MaxConnectionIdle: 5
  MaxConnectionAge: 5
  SessionPrefix: "session"
  CSRFPrefix: "csrf"
  SessionGrpcServicePort: ":5000"

HttpServer:
  Port: ":8000"
  PprofPort: ":8001"
  Timeout: 15
  ReadTimeout: 5
  WriteTimeout: 5
  CookieLifeTime: 44640
  SessionCookieName: "session_token"

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5556
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDbname: postgres
  PostgresqlSslmode: "disable"
  PgDriver: pgx
