### Tets if HTTP server is online
GET http://0.0.0.0:8000/ping

### View service config file
GET http://0.0.0.0:8000/ping/config

###
GET http://0.0.0.0:8000/ticket/5963035d-c8e2-48b2-9cf5-fd2cfc5a0a58

###
GET http://0.0.0.0:8000/ticket/list

###
POST http://0.0.0.0:8000/ticket

###
GET http://0.0.0.0:8000/ticket/list?reversed=true

###
GET http://0.0.0.0:8000/ticket/list?reversed=true&fields[author]=name,id

###
GET http://0.0.0.0:8000/ticket/list?fields[ticket]=some_field_to_be_returned&fields[author]=name

###
GET http://0.0.0.0:8000/ticket/list?reversed=true&fields[ticket]=some_field_to_be_returned,ticket_photos,ticket_description&fields[author]=id

###
GET http://0.0.0.0:8000/ticket/list?reversed=false&fields[ticket]=some_field_to_be_returned,ticket_photos,ticket_description&fields[author]=name,id
