### Tets if HTTP server is online
GET http://0.0.0.0:8000/ping

### View service config file
GET http://0.0.0.0:8000/ping/config

###
GET http://0.0.0.0:8000/ticket

###
GET http://0.0.0.0:8000/ticket/list

###
POST http://0.0.0.0:8000/ticket

{
  "owner_id": "595f3d55-3f65-4a0f-9895-452ed041478a",
  "name_short": "Short name example",
  "name_ext": "Name example",
  "description": "Description example",
  "amount": 10,
  "price": 1.4,
  "currency": 10,
  "priority": "Regular",
  "published": true
}
